export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const MESSAGES_FETCH_SUCCESS = "MESSAGES_FETCH_SUCCESS";
export const MESSAGES_LOAD_MORE_SUCCESS = "MESSAGES_LOAD_MORE_SUCCESS";
export const MESSAGES_FETCH_FAIL = "MESSAGES_FETCH_FAIL";
// export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
// export const MESSAGE_SEND_FAIL = "MESSAGE_SEND_FAIL";

export const ONLINE_USERS = "ONLINE_USERS";